### ISSUE TITLE
Using custom login actions?

### ISSUE THREAD

**Issue by popaulina** [marmelab/admin-on-rest#637]
As of 0.9.4, I had a custom login page and was using `this.props.authClient` to call auth functions, which was working. After upgrading to 1.0.1, this no longer works, and the documentation now says to use `userLogin` and `userLogout` but gives no example of how to use these actions. In the default login page, it is used as `this.props.userLogin` but trying to use this results in an error in my application that `this.props.userLogin is not a function`. I see that the function is also being imported with `import { userLogin as userLoginAction } from '../../actions/authActions';`. Does this need to be imported by hand from `lib/actions/authActions`? 
I have tried using `import { userLogin, userCheck } from 'admin-on-rest'` and doing `return userLogin({ token: 'Bearer ' + data.access_token }, this.props.location.state ? this.props.location.state.nextPathname : '/');`. The data is there, the line gets hit, but then `AUTH_LOGIN` is never called in authClient, so I am just constantly redirected to my login page. My authClient file is pretty much exactly what is in the example, except I set a token on login.

**Comment by djhi** [comment]
Hi,

You have to connect your custom Login page (using react-redux [connect](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)) and pass the `userLogin` action in the `mapDispatchToProps` parameter.

In the default Login page, this is done [here](https://github.com/marmelab/admin-on-rest/blob/master/src/mui/auth/Login.js#L144).

```js
import { connect } from 'react-redux';
import { userLogin } from '../../actions/authActions';

const MyLoginPage {
    ....
};

export default connect(undefined, { userLogin });
```
